test := buffer_test			# Name of the executable to be built (put into f_u_t_u_r_e_w_a_v_e/bin/test)
objs := buffer_test.o	   # List of object files for this test source

test_libs := libtinyfs.a libbuffer.a	# List of archives this test depends on

include $(base_dir)/src/test.mk			# Tests always include the test.mk
