lib := libbuffer.a	# Name of the archive to build for the project to link against
objs := buffer.o		# List of the object files to build into the archive

include $(base_dir)/src/lib.mk  # Libraries always include the lib.mk
